server:
  port: 8888
spring:
  application:
    name: spring-cloud-bus-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/birintsev/config.git
          default-label: master
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
